//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shoppingcart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string country { get; set; }
        public string city { get; set; }
        public string state { get; set; }
        public string postal_code { get; set; }
    }
}
